### ISSUE TITLE
Issue with GET Request Params in Version 1.7

### ISSUE THREAD

**Issue by ZB-Alex** [enmerk4r/Swiftlet#14]
Loving this module so far, thank you for all your hard work on it!

There seems to be a bug in version 1.7 where if I build some query parameters and attach them to a GET request, they seem to not be formatted correctly and I am getting errors from the server I am making a request from. I can roll back the version to 1.6 and I don't get the same issue, but when I roll back forward again (with the same grasshopper code and inputs) and get the failure response from my server. 

Let me know if there is a way to provide any more details to help resolve this issue. 

Thanks!

**Comment by enmerk4r** [comment]
Hi @ZB-Alex. Thanks for reporting! Due to some internal refactoring and a more stringent URL validation in version 1.7, passing query params as part of a URL is no longer allowed. Now you have to use the Create Query Param (CQP) component and then pass it to P input of the GET component. Let me know if this solves your issue
