### ISSUE TITLE
Extra files copied to Solution Output

### ISSUE THREAD

**Issue by thekaushikls** [enmerk4r/Swiftlet#16]
## When viewed on [https://github.dev/enmerk4r/Swiftlet](https://github.dev/enmerk4r/Swiftlet), there seem to be additional references.
![image](https://user-images.githubusercontent.com/50703773/232969188-b89eefdc-55cd-4e2f-b17c-1a1a481eb106.png)

## When building the solution, additional library files seem to be copied to the `bin` folder. But these are not included in the `.yak` file. So, are they needed in the first place?
![image](https://user-images.githubusercontent.com/50703773/232969768-18915dfa-5f50-4074-8947-794d6e9cac90.png)

**Comment by enmerk4r** [comment]
@thekaushikls A lot of these DLLs should not be redistributed, because they get loaded by the Rhino process:

```Eto.dll
GH_IO.dll
Grasshopper.dll
Rhino.UI.dll
RhinoCommon.dll
```
For all of these dlls "CopyLocal" should be sent to false. As a matter of fact, if you try to load a Grasshopper plugin that contains a Grasshopper.dll in it, Grasshopper will refuse to launch. But you do need those as references to actually build Swiftlet
