### ISSUE TITLE
Download file from Dropbox?

### ISSUE THREAD

**Issue by zohozer** [enmerk4r/Swiftlet#19]
Hi. I am in a search for a Grasshopper solution to retrieve the content of some files that are stored on Dropbox and do found this components.

I do tried to use the basic example with the "Basic Auth" in it, but unfortunately I can't get the desire files even if I do put correctly the URL, Username and Password but unfortunately I can't get the content of the file that I do need.

My file in Dropbox it is just a standard TXT file, nothing fancy, but even so, I can't get any result.

Please can you provide a working example for Dropbox files? Maybe it is something that I do not understand how to do.

Best regards.

**Comment by enmerk4r** [comment]
@zohozer  Have you tried enabling link sharing for your file and then feeding it to the GET component in Swiftlet? You might have to deconstruct the URL to separate the params from the rest of the path. But I would try that out first. Basic auth is an ancient and highly unsafe way of authenticating to an API, which is why modern services don't support it (including Dropbox). I added basic auth to Swiftlet simply for calling into legacy endpoints.

If link sharing doesn't work, then read Dropbox API documentation. You might have to generate an auth token to download your file through an API.
